HW2
================
Christina Dai cd3347

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.3     ✔ readr     2.1.4
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.0
    ## ✔ ggplot2   3.4.3     ✔ tibble    3.2.1
    ## ✔ lubridate 1.9.2     ✔ tidyr     1.3.0
    ## ✔ purrr     1.0.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(readxl)
```

### Problem 1

### Problem 2

Read and clean the Mr. Trash Wheel sheet:

``` r
mr_trash_tidy = 
  read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 1,
             range = "A2:N586") %>% 
  janitor::clean_names() %>% 
  mutate(homes_powered = (weight_tons * 500) / 30) %>% 
  mutate(year = as.numeric(year)) %>% 
  mutate(wheel_name = "mr_trash") %>% 
  relocate(wheel_name)
```

Do the same for the Professor Trash Wheel and Gwynnda datasets:

``` r
prof_trash_tidy = 
  read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 2,
             range = "A2:M108") %>% 
  janitor::clean_names() %>% 
  mutate(homes_powered = (weight_tons * 500) / 30) %>% 
  mutate(wheel_name = "prof_trash") %>% 
  relocate(wheel_name)
```

``` r
gwynnda_tidy = 
  read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet = 4,
             range = "A2:L157") %>% 
  janitor::clean_names() %>% 
  mutate(homes_powered = (weight_tons * 500) / 30) %>% 
  mutate(wheel_name = "gwynnda") %>% 
  relocate(wheel_name)
  gwynnda_cigs = gwynnda_tidy[1,10] + gwynnda_tidy[2,10] + gwynnda_tidy[3,10] + gwynnda_tidy[4,10] + gwynnda_tidy[5,10]
```

Combine all three datasets:

``` r
trash_wheels_tidy = 
  bind_rows(mr_trash_tidy, prof_trash_tidy, gwynnda_tidy)
```

In the combined dataset, which includes data from Mr. Trash Wheel,
Professor Trash Wheel, and Gwynnda Trash wheel, there are 845 rows. One
key variable in this dataset is `weight_tons`, which describes the
weight in tons of trash collected by each dumpster receiving trash from
each trash wheel. Another key variable is `homes_powered`, which
describes the amount of homes that are powered by the electricity
generated by the incineration of the trash collected. Other key
variables include trash types, such as `polystyrene` and
`glass bottles`. The dataset also includes information like year, month,
and date. For available data, the total amount of trash collected by
Professor Trash Wheel is 216.26. The total number of cigarette butts
collected by Gwynnda in July of 2021 is 1.63^{4}.

### Problem 3

Import and clean the MCI baseline dataset:

``` r
mci_baseline_tidy = 
  read_csv("./data/MCI_baseline.csv", skip = 1) %>% 
  janitor::clean_names() %>% 
  mutate(sex = recode(sex, `1` = "male", `0` = "female")) %>% 
  mutate(apoe4 = recode(apoe4, `1` = "carrier", `0` = "non-carrier")) %>% 
  filter(age_at_onset > current_age | age_at_onset == '.')
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
develop_mci = filter(mci_baseline_tidy, age_at_onset != '.')
carriers = filter(mci_baseline_tidy, apoe4 == "carrier")
```

The first step in this process is to read in the data using `read_csv`,
skipping the first row because it does not contain any data. Then, after
cleaning the names using `janitor::clean_names()`, we use `mutate()` to
recode the `sex` variable and `apoe4` variable to be more specific.
Lastly, using `filter`, we only include observations where
`age_at_onset` is either greater than `current_age` or the null value of
“.” to ensure that inclusion criteria is met. 483 participants were
recruited for this study, with 479 meeting inclusion criteria. 93
participants developed MCI during the study. The average baseline age is
65.0286013, while 30.0626305 is the proportion of women in the study
that are APOE4 carriers.

Now, do the same for the MCI amyloid dataset:

``` r
mci_amyloid_tidy = 
  read_csv("./data/mci_amyloid.csv", skip = 1) %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    baseline:time_8,
    names_to = "record_time",
    names_prefix = "time_",
    values_to = "amyloid"
  ) %>% 
  rename("id" = study_id)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

The first step here is the same as before: read the data using
`read_csv`. Then use `janitor::clean_names()` to standardize the
variable names. After that, we need to tidy our recording times by using
`pivot_longer`, which will combine all the recording times into one
variable, `record_time`, and amyloid values into `amyloid`. Now, each
observation corresponds to the amyloid value at each time of recording,
including baseline.

Now, check to see if some participants appear only in either dataset:

``` r
anti_join(mci_baseline_tidy, mci_amyloid_tidy, by = "id")
```

    ## # A tibble: 8 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ## 1    14        58.4 female        20 non-carrier 66.2        
    ## 2    49        64.7 male          16 non-carrier 68.4        
    ## 3    92        68.6 female        20 non-carrier .           
    ## 4   179        68.1 male          16 non-carrier .           
    ## 5   268        61.4 female        18 carrier     67.5        
    ## 6   304        63.8 female        16 non-carrier .           
    ## 7   389        59.3 female        16 non-carrier .           
    ## 8   412        67   male          16 carrier     .

There are 8 participants who don’t exist in both datasets: IDs 14, 49,
92, 179, 268, 304, 389, and 412. These participants only exist in the
baseline dataset, and were likely lost to follow-up.

Now, combine datasets together with only particpants that exist in both
datasets:

``` r
mci_combined = 
  inner_join(mci_baseline_tidy, mci_amyloid_tidy, by = "id")
```
